# Generated by Django 5.0 on 2023-12-12 00:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosProductos',
            fields=[
                ('CodigosID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CodigoID')),
                ('ProductoCodigo', models.CharField(choices=[('PR7', 'R7'), ('PR2', 'R2'), ('PR5', 'DEP550'), ('PR3', 'EP350'), ('M8e', '8500e'), ('M5e', '5000e'), ('M8', 'DGM8000'), ('M5', 'DEM500'), ('APX0', 'APX'), ('APX2', 'APX'), ('APX1', 'APX')], max_length=40, unique=True, verbose_name='Codigo de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProductos',
            fields=[
                ('TipoID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='TipoID')),
                ('TipoProducto', models.CharField(choices=[('RADIO MOVIL', 'Movil'), ('RADIO PORTATIL', 'Portatil'), ('RADIO APX', 'APX')], max_length=40, unique=True, verbose_name='Tipo de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False, verbose_name='ProductID')),
                ('Nombre', models.CharField(max_length=60, verbose_name='Nombre del producto')),
                ('Cantidad', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de producto')),
                ('Marca', models.CharField(max_length=60, verbose_name='Marca del producto')),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('Precio', models.FloatField(verbose_name='Precio')),
                ('Creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('Modificado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Modificacion')),
                ('Codigos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductCodigo', to='Core.codigosproductos', to_field='ProductoCodigo')),
            ],
        ),
    ]
