# Generated by Django 4.2.6 on 2024-11-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="excel_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="productos/excel/",
                verbose_name="Archivo Excel",
            ),
        ),
    ]
