# Generated by Django 4.2.6 on 2024-11-22 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0003_producto_excel_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="excel_file",
            new_name="pdf_file",
        ),
    ]
