# Generated by Django 4.2.6 on 2024-11-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0004_rename_excel_file_producto_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codigosproductos",
            name="ProductoCodigo",
            field=models.CharField(
                choices=[
                    ("PR7", "R7"),
                    ("PR2", "R2"),
                    ("PR5", "DEP550"),
                    ("PR3", "EP350"),
                    ("M8e", "8500e"),
                    ("M5e", "5000e"),
                    ("M8", "DGM8000"),
                    ("M5", "DEM500"),
                    ("APX", "APX0"),
                    ("APX", "APX2"),
                    ("APX", "APX1"),
                ],
                max_length=40,
                unique=True,
                verbose_name="Codigo de Producto",
            ),
        ),
    ]
