# Generated by Django 4.2.7 on 2024-12-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_codigosproductos_productocodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosproductos',
            name='ProductoCodigo',
            field=models.CharField(choices=[('PR7', 'R7'), ('PR2', 'R2'), ('PR5', 'DEP550'), ('PR3', 'EP350'), ('M8e', '8500e'), ('M5e', '5000e'), ('M8', 'DGM8000'), ('M5', 'DEM500'), ('APX0', 'APX0'), ('APX2', 'APX2'), ('APX1', 'APX1')], max_length=40, unique=True, verbose_name='Codigo de Producto'),
        ),
    ]
