# Generated by Django 5.0 on 2023-12-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False, verbose_name='OrderID')),
                ('Direccion', models.CharField(max_length=60, verbose_name='Direccion')),
                ('MetodoPago', models.CharField(default='PayPal', editable=False, max_length=30, verbose_name='MetodoPago')),
                ('PrecioTotal', models.IntegerField(verbose_name='Precio Compra')),
                ('Items', models.ManyToManyField(to='cart.cartitems')),
            ],
        ),
    ]
