# Generated by Django 4.2.6 on 2024-11-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "OrderID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="OrderID"
                    ),
                ),
                (
                    "User_email",
                    models.EmailField(
                        max_length=60, null=True, verbose_name="User_email"
                    ),
                ),
                (
                    "Direccion",
                    models.CharField(max_length=60, verbose_name="Direccion"),
                ),
                (
                    "MetodoPago",
                    models.CharField(
                        default="PayPal", max_length=30, verbose_name="MetodoPago"
                    ),
                ),
                ("PrecioTotal", models.IntegerField(verbose_name="Precio Compra")),
                (
                    "FechaCompra",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de compra"
                    ),
                ),
                ("Items", models.ManyToManyField(to="cart.cartitems")),
            ],
        ),
    ]
