# Generated by Django 5.0 on 2023-12-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='MetodoPago',
            field=models.CharField(default='PayPal', max_length=30, verbose_name='MetodoPago'),
        ),
    ]
