# Generated by Django 4.2.6 on 2024-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="User_region",
            field=models.CharField(
                max_length=70, null=True, verbose_name="Region_de_compra"
            ),
        ),
    ]
