# Generated by Django 5.0 on 2023-12-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_metodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='User_email',
            field=models.EmailField(max_length=60, null=True, verbose_name='User_email'),
        ),
    ]
