# Generated by Django 5.0 on 2023-12-12 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('UserID', models.AutoField(primary_key=True, serialize=False, verbose_name='UserID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('userType', models.CharField(choices=[('ADMINISTRADOR', 'Admin'), ('VENDEDOR', 'Seller'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=25, verbose_name='Tipo de usuario')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Cuentas',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('PerfilID', models.AutoField(primary_key=True, serialize=False, verbose_name='PerfilID')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre cliente')),
                ('Apellido', models.CharField(max_length=30, verbose_name='Apellido cliente')),
                ('afiliacion', models.CharField(max_length=60, verbose_name='Afiliacion')),
                ('Telefono', models.CharField(max_length=30, verbose_name='Telefono cliente')),
                ('Direccion', models.CharField(max_length=30, verbose_name='Direccion cliente')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
