# Generated by Django 4.2.7 on 2024-11-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfil_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='afiliacion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='Empresa',
            field=models.CharField(max_length=60, null=True, verbose_name='Empresa'),
        ),
    ]
