# Generated by Django 4.2.6 on 2024-11-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_perfil_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="Region",
            field=models.IntegerField(
                choices=[
                    (1, "Arica y Parinacota"),
                    (2, "Tarapacá"),
                    (3, "Antofagasta"),
                    (4, "Atacama"),
                    (5, "Coquimbo"),
                    (6, "Valparaíso"),
                    (7, "Región Metropolitana de Santiago"),
                    (8, "Libertador General Bernardo O'Higgins"),
                    (9, "Maule"),
                    (10, "Ñuble"),
                    (11, "Biobío"),
                    (12, "La Araucanía"),
                    (13, "Los Ríos"),
                    (14, "Los Lagos"),
                    (15, "Aysén del General Carlos Ibáñez del Campo"),
                    (16, "Magallanes y de la Antártica Chilena"),
                ],
                default=7,
                null=True,
                verbose_name="Region",
            ),
        ),
    ]
