# Generated by Django 4.2.6 on 2024-11-02 17:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "CartID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="CartID"
                    ),
                ),
                ("Fecha_Creado", models.DateTimeField(auto_now_add=True)),
                ("Completado", models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CartItems",
            fields=[
                (
                    "CartItemsID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="XID"
                    ),
                ),
                (
                    "Cantidad",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("fechaAgregado", models.DateTimeField(auto_now_add=True)),
                (
                    "Cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Carrito",
                        to="cart.carrito",
                    ),
                ),
                (
                    "Item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Items",
                        to="Core.producto",
                    ),
                ),
            ],
        ),
    ]
