# Generated by Django 5.0 on 2023-12-12 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('CartID', models.AutoField(primary_key=True, serialize=False, verbose_name='CartID')),
                ('Fecha_Creado', models.DateTimeField(auto_now_add=True)),
                ('Completado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('CartItemsID', models.AutoField(primary_key=True, serialize=False, verbose_name='XID')),
                ('Cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('fechaAgregado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
