# Generated by Django 5.0 on 2023-12-12 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0002_initial'),
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='UserCart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CarritoDeUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='Cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carrito', to='cart.carrito'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='Core.producto'),
        ),
    ]
