# Generated by Django 4.2.6 on 2024-11-02 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrito",
            name="UserCart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="CarritoDeUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
